# Generated by Django 3.2 on 2021-04-15 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='registration_date',
        ),
    ]
