# Generated by Django 3.2 on 2021-04-15 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med', '0002_remove_userprofile_registration_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='key',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='firstName',
            field=models.CharField(max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='secondName',
            field=models.CharField(max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='tel',
            field=models.CharField(max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='thirdName',
            field=models.CharField(max_length=30, null=True, verbose_name='Отчество'),
        ),
    ]
